//! [snippet1]
// We include what we need for the test
#include <gatb/gatb_core.hpp>
#include <DSK.hpp>
#include <fstream>

// We use the required packages
using namespace std;

/********************************************************************************/
class DSK2ASCII : public Tool
{
public:

    /** */
    DSK2ASCII () : Tool ("dsk2ascii")
    {
        getParser()->push_front (new OptionOneParam (STR_URI_OUTPUT, "output file",           true));
        getParser()->push_front (new OptionOneParam (STR_URI_FILE,   "file generated by dsk", true));
    }

    /** */
    void execute ()
    {
        // We get a handle on the HDF5 storage object.
        // Note that we use an auto pointer since the StorageFactory dynamically allocates an instance
        Storage* storage = StorageFactory(DSK::getStorageMode()).load (getInput()->getStr(STR_URI_FILE));
        LOCAL (storage);

        // We get the solid kmers collection 1) from the 'dsk' group  2) from the 'solid' collection
        Partition<Kmer<>::Count>& solidKmers = storage->getGroup("dsk").getPartition<Kmer<>::Count> ("solid");

        // We create a Model instance. It will help to dump the kmers in
        // a human readable form (ie as a string of nucleotides)
        Kmer<>::ModelCanonical model (atol (storage->getGroup("dsk").getProperty ("kmer_size").c_str()));

        // We create the output file
        fstream output (getInput()->getStr(STR_URI_OUTPUT).c_str(), std::fstream::out);

        // We iterate (through a lambda expression) the solid kmers from the retrieved collection
        Iterator<Kmer<>::Count>* itKmers = createIterator (solidKmers.iterator(), solidKmers.getNbItems(), "parsing");
        LOCAL(itKmers);

        for (itKmers->first(); !itKmers->isDone(); itKmers->next())
        {
            const Kmer<>::Count& count = itKmers->item();
            output << model.toString(count.value) << " " << count.abundance << endl;
        }

        output.close();

        /** We gather some statistics. */
        getInfo()->add (1, "stats");
        getInfo()->add (2, "nb_kmers", "%ld", solidKmers.getNbItems());
    }
};

/********************************************************************************/
/*                       Dump solid kmers in ASCII format                       */
/********************************************************************************/
int main (int argc, char* argv[])
{
    try
    {
        DSK2ASCII().run (argc, argv);
    }
    catch (Exception& e)
    {
        std::cout << "EXCEPTION: " << e.getMessage() << std::endl;
        return EXIT_FAILURE;
    }
}
//! [snippet1]
